# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from pydantic_cpd.cdp.base import CDPModel

from .types import *


class RecordingStateChangedEvent(CDPModel):
    """
    Called when the recording state for the service has been updated.
    """

    is_recording: bool
    service: ServiceName


class BackgroundServiceEventReceivedEvent(CDPModel):
    """
    Called with all existing backgroundServiceEvents when enabled, and all new events
    afterwards if enabled and recording.
    """

    background_service_event: BackgroundServiceEvent
