# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from pydantic_cpd.cdp.base import CDPModel

from .types import *


class AcceptedEvent(CDPModel):
    """
    Informs that port was successfully bound and got a specified connection id.
    """

    port: int
    connection_id: str
