# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from __future__ import annotations

from typing import TYPE_CHECKING
from dataclasses import dataclass
from enum import StrEnum
from cdpify.shared.models import CDPModel

if TYPE_CHECKING:
    from cdpify.domains import dom, page


class OverlayEvent(StrEnum):
    INSPECT_NODE_REQUESTED = "Overlay.inspectNodeRequested"
    NODE_HIGHLIGHT_REQUESTED = "Overlay.nodeHighlightRequested"
    SCREENSHOT_REQUESTED = "Overlay.screenshotRequested"
    INSPECT_PANEL_SHOW_REQUESTED = "Overlay.inspectPanelShowRequested"
    INSPECTED_ELEMENT_WINDOW_RESTORED = "Overlay.inspectedElementWindowRestored"
    INSPECT_MODE_CANCELED = "Overlay.inspectModeCanceled"


@dataclass(kw_only=True)
class InspectNodeRequestedEvent(CDPModel):
    """
    Fired when the node should be inspected. This happens after call to
    `setInspectMode` or when user manually inspects an element.
    """

    backend_node_id: dom.BackendNodeId


@dataclass(kw_only=True)
class NodeHighlightRequestedEvent(CDPModel):
    """
    Fired when the node should be highlighted. This happens after call to
    `setInspectMode`.
    """

    node_id: dom.NodeId


@dataclass(kw_only=True)
class ScreenshotRequestedEvent(CDPModel):
    """
    Fired when user asks to capture screenshot of some area on the page.
    """

    viewport: page.Viewport


@dataclass(kw_only=True)
class InspectPanelShowRequestedEvent(CDPModel):
    """
    Fired when user asks to show the Inspect panel.
    """

    backend_node_id: dom.BackendNodeId


@dataclass(kw_only=True)
class InspectedElementWindowRestoredEvent(CDPModel):
    """
    Fired when user asks to restore the Inspected Element floating window.
    """

    backend_node_id: dom.BackendNodeId


@dataclass(kw_only=True)
class InspectModeCanceledEvent(CDPModel):
    """
    Fired when user cancels the inspect mode.
    """

    pass
