# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from pydantic_cpd.cdp.base import CDPModel

from .types import *


class DragInterceptedEvent(CDPModel):
    """
    Emitted only when `Input.setInterceptDrags` is enabled. Use this data with
    `Input.dispatchDragEvent` to restore normal drag and drop behavior.
    """

    data: DragData
