# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from pydantic_cpd.cdp.base import CDPModel

from .types import *


class DomStorageItemAddedEvent(CDPModel):
    storage_id: StorageId
    key: str
    new_value: str


class DomStorageItemRemovedEvent(CDPModel):
    storage_id: StorageId
    key: str


class DomStorageItemUpdatedEvent(CDPModel):
    storage_id: StorageId
    key: str
    old_value: str
    new_value: str


class DomStorageItemsClearedEvent(CDPModel):
    storage_id: StorageId
