# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

from pydantic_cpd.cdp.base import CDPModel

from .types import *


class LoadCompleteEvent(CDPModel):
    """
    The loadComplete event mirrors the load complete event sent by the browser to
    assistive technology when the web page has finished loading.
    """

    root: AXNode


class NodesUpdatedEvent(CDPModel):
    """
    The nodesUpdated event is sent every time a previously requested node has changed
    the in tree.
    """

    nodes: list[AXNode]
